name: Setup
description: Setup the environment for the runner

runs:
  using: composite
  steps:
    - uses: jdx/mise-action@v4
    - uses: actions/cache@v6
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-bun-
    - run: bun install --frozen-lockfile
      shell: bash
